# Module manifest for module 'xModifyXML'
# Generated by: Greg Rowe
# Generated on: 2017.11.20

@{
    
    RootModule = 'xModifyXML.psm1'
    ModuleVersion = '0.1'
    GUID = '9688b6c6-c859-46df-acef-b88cf89f4b0a'
    Author = 'Greg Rowe'
    # Copyright = ''
    Description = 'Powershell module for easily modifying complex XML'
    PowerShellVersion = '5.0'
    # CompatiblePSEditions = @()
    FunctionsToExport = @( 'Get-XmlNode', 'Set-XmlNode', 'Add-XmlNode', 'Remove-XmlNode' )
    DscResourcesToExport = @( 'xXmlNode' )
    # CompanyName = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # CmdletsToExport = @()
    # VariablesToExport = '*'
    # AliasesToExport = @()
    # ModuleList = @()
    # FileList = @()
    
    PrivateData = @{
        PSData = @{
            Tags = @( 'XML', 'DSC', 'XmlNode', 'xXmlNode' )
            LicenseUri = 'https://www.gnu.org/licenses/gpl-3.0.en.html'
            ProjectUri = 'https://github.com/gaxor/xModifyXML'
            # IconUri = ''
            # ReleaseNotes = ''
        } # End of PSData hashtable
    } # End of PrivateData hashtable
    
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
    
    }
    